# Generated by Django 4.2.5 on 2023-09-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yellow',
            name='id',
        ),
        migrations.AlterField(
            model_name='yellow',
            name='Start',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
