# Generated by Django 4.2.5 on 2023-09-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesearch', '0002_remove_yellow_id_alter_yellow_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='yellow',
            name='id',
            field=models.BigAutoField(auto_created=True, default=11, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yellow',
            name='Start',
            field=models.IntegerField(),
        ),
    ]
