# Generated by Django 4.2.5 on 2023-09-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genesearch', '0003_yellow_id_alter_yellow_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='green',
            name='yellow',
        ),
    ]
